export enum EnumUnitId {
    Infantry = 1,
    Mech = 2,
    MdTank = 3,
    Tank = 4,
    Recon = 5,
    APC = 6,
    Artillery = 7,
    Rocket = 8,
    AntiAir = 9,
    Missile = 10,
    Fighter = 11,
    Bomber = 12,
    BCopter = 13,
    TCopter = 14,
    Battleship = 15,
    Cruiser = 16,
    Lander = 17,
    Sub = 18,
    BlackBoat = 28,
    Carrier = 29,
    Stealth = 30,
    BlackBomb = 968731,
    MegaTank = 1141438,
    Neotank = 46,
    Piperunner = 960900,
}

export enum EnumUnitName {
    Mech = "Mech",
    Infantry = "Infantry",
    Recon = "Recon",
    TCopter = "T-Copter",
    APC = "APC",
    Artillery = "Artillery",
    Tank = "Tank",
    BlackBoat = "Black Boat",
    AntiAir = "Anti-Air",
    BCopter = "B-Copter",
    Lander = "Lander",
    Missile = "Missile",
    Rocket = "Rocket",
    MdTank = "Md.Tank",
    Cruiser = "Cruiser",
    Sub = "Sub",
    Fighter = "Fighter",
    Piperunner = "Piperunner",
    Neotank = "Neotank",
    Bomber = "Bomber",
    Stealth = "Stealth",
    BlackBomb = "Black Bomb",
    Battleship = "Battleship",
    MegaTank = "Mega Tank",
    Carrier = "Carrier",
}